VIRTUAL_WIDTH = 768
VIRTUAL_HEIGHT = 432

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

PLAYER_WALK_SPEED = 250

MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

TILE_FLOOR = 'floor1'
TILE_WALL = 'wall1'